name = "KernelForecasting"
uuid = "9a7597b4-ac1c-49a7-9aa4-007f937c06b8"
version = "0.1.0"
authors = ["Nicholas Engelking <moblin88@me.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10.10"
