name = "KernelForecasting"
uuid = "9a7597b4-ac1c-49a7-9aa4-007f937c06b8"
authors = ["Nicholas Engelking <moblin88@me.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
